-----Objective: Create a Trigger to Log Product Changes
--Trigger Name: log_product_changes
--Table: Products
--Triggering Events: BEFORE INSERT, BEFORE UPDATE, BEFORE DELETE

sql

CREATE TABLE ProductChangeLog (
    LogID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ProductID NUMBER,
    ChangeType VARCHAR2(10),
    OldQuantity NUMBER,
    NewQuantity NUMBER,
    ChangeDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ChangedBy VARCHAR2(100) -- You can store the username or identifier of the user making the change
);

---Explanation of the Log Table----

--LogID: A unique identifier for each log entry.
--ProductID: The ID of the product that was changed.
--ChangeType: Indicates whether the change was an INSERT, UPDATE, or DELETE.
--OldQuantity: The quantity of the product before the change (for updates and deletes).
--NewQuantity: The quantity of the product after the change (for inserts and updates).
--ChangeDate: The timestamp when the change occurred.
--ChangedBy: The user who made the change (you may need to set this programmatically).


CREATE OR REPLACE TRIGGER log_product_changes
BEFORE INSERT OR UPDATE OR DELETE ON Products
FOR EACH ROW
DECLARE
    v_ChangedBy VARCHAR2(100);
BEGIN
    -- Get the username or identifier of the user making the change (if available)
    v_ChangedBy := USER; -- You can replace this with actual logic if needed

    IF INSERTING THEN
        INSERT INTO ProductChangeLog (ProductID, ChangeType, NewQuantity, ChangedBy)
        VALUES (:NEW.ProductID, 'INSERT', :NEW.STOCKQUANTITY, v_ChangedBy);

    ELSIF UPDATING THEN
        INSERT INTO ProductChangeLog (ProductID, ChangeType, OldQuantity, NewQuantity, ChangedBy)
        VALUES (:OLD.ProductID, 'UPDATE', :OLD.STOCKQUANTITY, :NEW.STOCKQUANTITY, v_ChangedBy);

    ELSIF DELETING THEN
        INSERT INTO ProductChangeLog (ProductID, ChangeType, OldQuantity, ChangedBy)
        VALUES (:OLD.ProductID, 'DELETE', :OLD.STOCKQUANTITY, v_ChangedBy);
    END IF;
END;
/

--Check that the trigger has been created successfully without errors:

SELECT TRIGGER_NAME FROM USER_TRIGGERS WHERE TRIGGER_NAME = 'LOG_PRODUCT_CHANGES';

--Test the Trigger:

INSERT INTO Products (ProductID, ProductName, VendorID, Category, Price, STOCKQUANTITY)
VALUES (10, 'Test Product', 1, 'Accessories', 1000, 20);


---Check change Logs:

SELECT * FROM ProductChangeLog ORDER BY ChangeDate DESC;

