-- Create  Users Table
CREATE TABLE Users (
    UserID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Username VARCHAR2(50) UNIQUE NOT NULL,
    Password VARCHAR2(255) NOT NULL,
    Role VARCHAR2(10) CHECK (Role IN ('Customer', 'Vendor', 'Admin')) NOT NULL,
    Email VARCHAR2(100) NOT NULL,
    PhoneNumber VARCHAR2(15)
);

-- Create Vendors Table
CREATE TABLE Vendors (
    VendorID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserID NUMBER NOT NULL,
    StoreName VARCHAR2(100) NOT NULL,
    Location VARCHAR2(100),
    ContactEmail VARCHAR2(100),
    ContactPhone VARCHAR2(15),
    VendorStatus VARCHAR2(10) CHECK (VendorStatus IN ('Active', 'Inactive')),
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

-- Create Products Table
CREATE TABLE Products (
    ProductID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ProductName VARCHAR2(100) NOT NULL,
    VendorID NUMBER NOT NULL,
    Category VARCHAR2(50),
    Price NUMBER(10, 2) NOT NULL,
    StockQuantity NUMBER NOT NULL,
    FOREIGN KEY (VendorID) REFERENCES Vendors(VendorID)
);

-- Create Orders Table
CREATE TABLE Orders (
    OrderID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CustomerID NUMBER NOT NULL,
    OrderDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TotalAmount NUMBER(10, 2) NOT NULL,
    PaymentStatus VARCHAR2(10) CHECK (PaymentStatus IN ('Paid', 'Pending')) NOT NULL,
    ShippingStatus VARCHAR2(10) CHECK (ShippingStatus IN ('Shipped', 'Pending')) NOT NULL,
    ShippingAddress VARCHAR2(255),  -- Added ShippingAddress field
    FOREIGN KEY (CustomerID) REFERENCES Users(UserID)
);

-- Create OrderDetails Table
CREATE TABLE OrderDetails (
    OrderDetailID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OrderID NUMBER NOT NULL,
    ProductID NUMBER NOT NULL,
    Quantity NUMBER NOT NULL,
    Price NUMBER(10, 2) NOT NULL,
    FOREIGN KEY (OrderID) REFERENCES Orders(OrderID),
    FOREIGN KEY (ProductID) REFERENCES Products(ProductID)
);

-- Create Payments Table
CREATE TABLE Payments (
    PaymentID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OrderID NUMBER NOT NULL,
    PaymentMethod VARCHAR2(50),
    PaymentAmount NUMBER(10, 2) NOT NULL,
    PaymentDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (OrderID) REFERENCES Orders(OrderID)
);

-- Create Shipping Table
CREATE TABLE Shipping (
    ShippingID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OrderID NUMBER NOT NULL,
    ShippingAddress VARCHAR2(255) NOT NULL,
    ShippingMethod VARCHAR2(50),
    ShippingCost NUMBER(10, 2),
    ShippingDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- Added ShippingDate timestamp
    FOREIGN KEY (OrderID) REFERENCES Orders(OrderID)
);

-- Create Wishlists Table
CREATE TABLE Wishlists (
    WishlistID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CustomerID NUMBER NOT NULL,
    ProductID NUMBER NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- Added CreatedAt timestamp
    FOREIGN KEY (CustomerID) REFERENCES Users(UserID),
    FOREIGN KEY (ProductID) REFERENCES Products(ProductID)
);
-- Create Reviews Table
CREATE TABLE Reviews (
    ReviewID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ProductID NUMBER NOT NULL,
    CustomerID NUMBER NOT NULL,
    Rating NUMBER CHECK (Rating BETWEEN 1 AND 5),
    ReviewText CLOB,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  -- Added CreatedAt timestamp
    FOREIGN KEY (ProductID) REFERENCES Products(ProductID),
    FOREIGN KEY (CustomerID) REFERENCES Users(UserID)
);


-- Create Indexes for Performance Optimization
-- Index on ProductID for Reviews table

CREATE INDEX idx_product_id ON Reviews(ProductID);

-- Index on VendorID for Products table
CREATE INDEX idx_vendor_id ON Products(VendorID);

